INSERT INTO directors (name, age) VALUES
                                     ('Christopher Nolan', 51),
                                     ('Quentin Tarantino', 58),
                                     ('Martin Scorsese', 79),
                                     ('Steven Spielberg', 75),
                                     ('Alfred Hitchcock', 80),
                                     ('Stanley Kubrick', 70),
                                     ('Akira Kurosawa', 88),
                                     ('Francis Ford Coppola', 82),
                                     ('Spike Lee', 64),
                                     ('James Cameron', 67),
                                     ('David Fincher', 59),
                                     ('Tim Burton', 63),
                                     ('Woody Allen', 86),
                                     ('Pedro Almodóvar', 72),
                                     ('Clint Eastwood', 91),
                                     ('Ridley Scott', 84),
                                     ('George Lucas', 77),
                                     ('Ang Lee', 67),
                                     ('Peter Jackson', 60),
                                     ('Michael Bay', 57);
